import type { Metadata } from 'next';
import './globals.scss';
import { Header } from '@/components/Header';
import { AppProvider } from '@/AppContext';

export const metadata: Metadata = {
  title: 'Tech Site',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
